#!/usr/bin/env python3
""" Factor numbers """
import sys

def read_numbers_from_file(file_name):
    """Read numbers from a file and return them as a list"""
    try:
        with open(file_name, "r", encoding="utf-8") as file:
            lines = file.readlines()
        return [int(line) for line in lines]
    except FileNotFoundError:
        print(f"Error: File '{file_name}' not found.")
        sys.exit(1)

def factorize_number(n):
    """Factorize a given number and print its prime factors"""
    for i in range(2, n + 1):
        while n % i == 0:
            print(f"{n}={n // i}*{i}")
            n //= i
            break

def factorize_numbers(numbers):
    """Factorize each number in the list"""
    for number in numbers:
        factorize_number(number)

if len(sys.argv) == 2:
    numbers = read_numbers_from_file(sys.argv[1])
    factorize_numbers(numbers)

