#!/usr/bin/env python3
""" Factor numbers """
from sys import argv

def read_numbers_from_file(file_name):
    """ Read numbers from a file and return them as a list """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    numbers_to_factor = [int(line) for line in lines]
    return numbers_to_factor

def factorize_number(number):
    """ Factorize a given number and print its prime factors """
    for i in range(1, number):
        if number == (number // i) * i:
            print("{} = {} * {}".format(number, number // i, i))
            break

def factorize_numbers(numbers):
    """ Factorize each number in the list """
    for num in numbers:
        factorize_number(num)

if len(argv) == 2:
    numbers_list = read_numbers_from_file(argv[1])
    factorize_numbers(numbers_list)

